title: Video Games are Changing the World! 
author: No_Manz_Sky
email: brendanrfairfield2012@gmail.com
description: 
Video Games are awesome and have the potential to transform the world :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  No_Manz_Sky # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
